# Generated by Django 3.0.5 on 2020-05-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200511_1045'),
        ('items', '0003_auto_20200518_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_base_price', to='core.Price'),
        ),
    ]
