# Generated by Django 3.0.5 on 2020-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200511_1045'),
        ('items', '0004_auto_20200519_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'slug')},
        ),
    ]
