# Generated by Django 3.0.5 on 2020-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200519_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembooking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcontract',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
