# Generated by Django 3.0.5 on 2020-05-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200519_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail_original',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='thumbnail'),
        ),
    ]
