# Generated by Django 3.0.5 on 2020-05-22 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200522_1209'),
        ('items', '0007_auto_20200521_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attachment',
            field=models.FileField(blank=True, help_text='This file will be attached to the confirmation mail', null=True, upload_to='', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_base_price', to='core.Price', verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('v', 'vehicles'), ('t', 'tools'), ('e', 'electronics'), ('p', 'photography'), ('vi', 'video'), ('o', 'other')], default='o', max_length=3, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contract_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.ItemContractProcedure', verbose_name='Contract procedure'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_id',
            field=models.CharField(blank=True, help_text='ID field for bardcodes etc.', max_length=100, null=True, verbose_name='Custom ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damages',
            field=models.TextField(blank=True, null=True, verbose_name='Damages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='donation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.TextField(blank=True, help_text='These instructions will be included in the confirmation mail text', null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='maximum_duration',
            field=models.IntegerField(default=0, help_text='Maximimum duration the item can be lent. Value of 0 means unlimited.', verbose_name='Maximum duration'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_owner',
            field=models.CharField(blank=True, help_text='Which entity bought or donated the item?', max_length=255, null=True, verbose_name='Original owner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.Actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_purchase_price', to='core.Price', verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='replacement_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_replacement_price', to='core.Price', verbose_name='Replacement price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='self_pickup',
            field=models.CharField(choices=[('n', 'not allowed'), ('l', 'limited'), ('a', 'allowed')], default='n', max_length=2, verbose_name='Self pickup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_no',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(default='p', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail_original',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('h', 'hours'), ('d', 'days')], default='d', max_length=3, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.ItemContract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='dtend',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='dtstart',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='itembooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='itemcontract',
            name='items',
            field=models.ManyToManyField(related_name='contracts', through='items.ItemBooking', to='items.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemcontract',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='itemcontractprocedure',
            name='self_pickup_group',
            field=models.ManyToManyField(blank=True, help_text="The group granted self pickup if item's self pickup is limited", to='core.Actor', verbose_name='Self pickup group'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='items.Item', verbose_name='Item'),
        ),
    ]
