# Generated by Django 3.0.5 on 2020-05-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200523_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembooking',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='items.ItemContract', verbose_name='Contract'),
        ),
    ]
