# Generated by Django 3.0.5 on 2020-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20200523_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='replacement_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Replacement price'),
        ),
    ]
