# Generated by Django 3.1 on 2020-10-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20201004_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contract_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemcontractprocedure', verbose_name='Contract procedure'),
        ),
    ]
