# Generated by Django 3.0.5 on 2020-04-17 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEPA',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PaymentMethod')),
                ('creditor_id', models.CharField(max_length=25, verbose_name='SEPA Creditor Identifier')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BankAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.paymentmethod',),
        ),
        migrations.CreateModel(
            name='SEPAMandate',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.contract',),
        ),
        migrations.CreateModel(
            name='SEPADirectDebitXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor_identifier', models.CharField(max_length=25)),
                ('xml_no', models.CharField(db_index=True, max_length=19)),
                ('full_xml_no', models.CharField(db_index=True, max_length=190)),
                ('collection_date', models.DateField()),
                ('name', models.CharField(max_length=70)),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=11)),
                ('batch', models.BooleanField(blank=True, default=True, verbose_name='Batch booking')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('file', models.FileField(upload_to='')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEPADirectDebitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endtoend_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'closed')], default='o', max_length=2)),
                ('name', models.CharField(max_length=70)),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=11)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('sepa_type', models.CharField(default='RCUR', max_length=4)),
                ('collection_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=140)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sepa_dd_creditor', to='core.Actor')),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sepa_dd_debitor', to='core.Actor')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sepa.SEPAMandate')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sepa.SEPA')),
                ('sepa_dd_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sepa.SEPADirectDebitXML')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
