# Generated by Django 3.0.5 on 2020-04-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0053_auto_20200416_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEPAMandate',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.contract',),
        ),
        migrations.CreateModel(
            name='SEPA',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PaymentMethod')),
                ('creditor_id', models.CharField(max_length=25, verbose_name='SEPA Creditor Identifier')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BankAccount')),
                ('mandate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sepa.SEPAMandate')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.paymentmethod',),
        ),
    ]
