# Generated by Django 3.0.5 on 2020-04-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepa',
            name='mandate',
        ),
    ]
