# Generated by Django 3.0.5 on 2020-04-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200427_1337'),
        ('sepa', '0003_auto_20200419_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='debitor',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sepadirectdebitpayment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sepadirectdebitpayment',
            name='payment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Payment'),
            preserve_default=False,
        ),
    ]
