# Generated by Django 3.0.5 on 2020-04-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepa', '0004_auto_20200427_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepadirectdebitpayment',
            name='sepa_dd_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sepa.SEPADirectDebitXML'),
        ),
    ]
