stages:
  - build
  - test
  - demo
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/resource-hub/resource-hub
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME

build:
  stage: build
  tags:
    - shell
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker build -t ${CONTAINER_TEST_IMAGE} .
    - docker push ${CONTAINER_TEST_IMAGE}

test:
  stage: test
  tags:
    - shell
  only:
    - master
  script:
    - cat ${TEST_ENV} > .env
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull ${CONTAINER_TEST_IMAGE}
    - docker-compose -f docker-compose.test.yml -p ci up --abort-on-container-exit
    - rm .env
  coverage: '/TOTAL.*\s(\d+)%/'

demo:
  stage: demo
  tags:
    - shell
  only:
    - master
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "${DEMO_SSH_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cat ${DEMO_ENV} > demo.env
    - scp demo.env demo@${DEMO_SERVER_IP}:${DEMO_PATH}/.env
    - ssh demo@${DEMO_SERVER_IP} "chmod 600 ${DEMO_PATH}/.env"
    - rm demo.env
    - scp docker-compose.demo.yml demo@${DEMO_SERVER_IP}:${DEMO_PATH}/docker-compose.yml
    - ssh demo@${DEMO_SERVER_IP} "cd ${DEMO_PATH} && docker-compose stop && docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com && docker pull ${CONTAINER_TEST_IMAGE} && docker-compose -f docker-compose.yml up -d"

deploy:
  stage: deploy
  tags:
    - shell
  only:
    - master
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "${DEPLOY_SSH_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cat ${DEPLOY_ENV} > deploy.env
    - scp demo.env deploy@${DEPLOY_SERVER_IP}:${DEPLOY_PATH}/.env
    - ssh deploy@${DEPLOY_SERVER_IP} "chmod 600 ${DEPLOY_PATH}/.env"
    - rm deploy.env
    - scp docker-compose.demo.yml deploy@${DEPLOY_SERVER_IP}:${DEPLOY_PATH}/docker-compose.yml
    - ssh deploy@${DEPLOY_SERVER_IP} "cd ${DEPLOY_PATH} && docker-compose stop && docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com && docker pull ${CONTAINER_TEST_IMAGE} && docker-compose -f docker-compose.yml up -d"
