stages:
  - build
  - test

variables:
  CONTAINER_IMAGE: registry.gitlab.com/resource-hub/resource-hub
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME

build:
  stage: build
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  tags:
    - shell
  script:
    - pwd
    - echo $TEST_ENV > .env
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker-compose.ci.yml -p ci up --abort-on-container-exit
  coverage: '/TOTAL.*\s(\d+)%/'
