version: '3'

services:
  app:
    image: registry.gitlab.com/campfireman/devop:${CI_BUILD_REF_NAME}
    command: bash -c "coverage run --source='.' manage.py test && coverage report"
    links:
      - postgres

  postgres:
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
