version: '3'

services:
  app:
    image: registry.gitlab.com/resource-hub/resource-hub:master
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.demo
    env_file:
      .env
    volumes:
      - /var/www/resource-hub-demo/static:/static
      - /var/www/resource-hub-demo/media:/media
    command: bash -c "cd src; python3 manage.py collectstatic --noinput && python3 manage.py migrate && gunicorn --bind 0.0.0.0:${DJANGO_PORT} resource_hub.wsgi:application"
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    network_mode: host