version: '3'

services:
  postgres:
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: django_test
      POSTGRES_PASSWORD: django_test
      POSTGRES_DB: django_test

  app:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.test
    image: registry.gitlab.com/resource-hub/resource-hub:${CI_BUILD_REF_NAME}
    command: bash -c "cd src; coverage run --source='.' manage.py test && coverage report"
    links:
      - postgres
