version: "3"

services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server

  worker:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.demo
    env_file:
      - .env
    image: registry.gitlab.com/resource-hub/resource-hub:master
    command: bash -c 'cd src && python3 manage.py rqworker default high low'
    extra_hosts:
      - "dockerhost:${DOCKER_BRIDGE}"

  scheduler:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      - .env
    restart: on-failure
    image: registry.gitlab.com/resource-hub/resource-hub:master
    volumes:
      - ./:/site:rw
    command: bash -c 'rqscheduler --host redis --port 6379'

  app:
    image: registry.gitlab.com/resource-hub/resource-hub:master
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.demo
    env_file: .env
    volumes:
      - ${DEMO_PATH}/static:/static
      - ${DEMO_PATH}/media:/media
    command: bash -c "cd src &&  python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py init_schedule && daphne -b 0.0.0.0 -p ${DJANGO_PORT} resource_hub.asgi:application"
    links:
      - redis
    extra_hosts:
      - "dockerhost:${DOCKER_BRIDGE}"
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
