version: '3'

services:
  postgres:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:alpine
    command: redis-server

  app:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      .env
    image: registry.gitlab.com/resource-hub/resource-hub:${CI_BUILD_REF_NAME}
    command: bash -c "cd src; coverage run --source='.' manage.py test && coverage report"
    links:
      - postgres
