version: '3'

services:
  postgres:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django

  app:
    build: ./
    command: bash -c 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./:/site:rw
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  
