version: '3'

services:
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ./:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    logging:
      driver: none # disable logging

  redis:
    image: redis:alpine
    command: redis-server

  mail:
    image: djfarrelly/maildev:latest
    command: maildev -s 8025 -w 8080
    ports: 
      - "8080:8080"

  worker:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      - .env
    image: app
    volumes:
      - ./:/site:rw
    command: bash -c 'cd src && python3 manage.py rqworker default high low'
    
  scheduler:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      - .env
    restart: on-failure
    image: app
    volumes:
      - ./:/site:rw
    command: bash -c 'rqscheduler --host redis --port 6379'

  app:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      - .env
    build: ./
    image: app
    command: bash -c 'cd src && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py init_schedule && python3 manage.py runserver --settings=resource_hub.settings.dev 0.0.0.0:${DJANGO_PORT}'
    volumes:
      - ./:/site:rw
    depends_on:
      - postgres
      - redis
      - worker
      - mail
    links:
      - redis
      - mail
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

volumes:
  site: