version: '3'

services:
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server

  app:
    environment:
      DJANGO_SETTINGS_MODULE: resource_hub.settings.dev
    env_file:
      - .env
    build: ./
    command: bash -c 'cd src; python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver --settings=resource_hub.settings.dev 0.0.0.0:8000'
    volumes:
      - ./:/site:rw
    depends_on:
      - postgres
      - redis
    links:
      - redis
    ports:
      - "8000:8000"
  
