# Generated by Django 3.0.3 on 2020-02-12 23:10

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20200212_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('is_public', models.BooleanField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('thumbnail_original', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueUsageContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contract')),
                ('equipment', models.ManyToManyField(to='venues.Equipment')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='venues.Event')),
            ],
            bases=('core.contract',),
        ),
        migrations.CreateModel(
            name='VenueContractProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='terms and conditions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('tax_rate', models.IntegerField(blank=True, default=0, verbose_name='tax rate applied to prices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_per_h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_price_per_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equipment', models.ManyToManyField(blank=True, to='venues.Equipment')),
                ('payment_methods', models.ManyToManyField(blank=True, to='core.PaymentMethod')),
                ('trigger', models.ManyToManyField(blank=True, related_name='procedure', to='core.ContractTrigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('thumbnail_original', models.ImageField(blank=True, upload_to='images/')),
                ('bookable', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('booking_procedure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.VenueContractProcedure')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gallery')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_created_by', to='core.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_actor', to='core.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Room'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='venues.EventTag'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_updated_by', to='core.Actor'),
        ),
    ]
