# Generated by Django 3.0.3 on 2020-02-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PaymentMethod')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BankAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.paymentmethod',),
        ),
    ]
