# Generated by Django 2.2.4 on 2019-11-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20191122_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price_per_h', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_price_per_d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('negiotiable', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
