# Generated by Django 3.0 on 2019-12-08 22:24

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191208_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
