# Generated by Django 3.0.3 on 2020-02-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200210_2237'),
        ('rooms', '0003_auto_20200103_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_price_per_d',
        ),
        migrations.RemoveField(
            model_name='room',
            name='negiotiable',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_h',
        ),
        migrations.AddField(
            model_name='room',
            name='bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VenueUsageContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contract')),
                ('equipment', models.ManyToManyField(to='rooms.Equipment')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rooms.Event')),
            ],
            bases=('core.contract',),
        ),
        migrations.CreateModel(
            name='VenueContractProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='terms and conditions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('tax_rate', models.IntegerField(default=0, verbose_name='tax rate applied to prices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_per_h', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_price_per_d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('equipment', models.ManyToManyField(to='rooms.Equipment')),
                ('payment_methods', models.ManyToManyField(to='core.PaymentMethod')),
                ('trigger', models.ManyToManyField(to='core.ContractTrigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='booking_procedure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.VenueContractProcedure'),
        ),
    ]
