# Generated by Django 3.0 on 2019-12-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191209_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='thumbnail_orginal',
            new_name='thumbnail_original',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='thumbnail_orginal',
            new_name='thumbnail_original',
        ),
    ]
