# Generated by Django 3.0.3 on 2020-02-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200210_2237'),
        ('rooms', '0004_auto_20200210_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='rooms.Equipment'),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='max_price_per_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='core.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='price_per_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='tax_rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='tax rate applied to prices'),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='trigger',
            field=models.ManyToManyField(blank=True, to='core.ContractTrigger'),
        ),
    ]
