# Generated by Django 3.0.5 on 2020-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200418_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='typ',
            field=models.CharField(choices=[('i', 'info'), ('a', 'action')], default='a', max_length=2),
            preserve_default=False,
        ),
    ]
