# Generated by Django 3.0.3 on 2020-02-23 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state'),
        ),
        migrations.AddField(
            model_name='payment',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state'),
        ),
    ]
