# Generated by Django 3.0.5 on 2020-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
