# Generated by Django 3.0.3 on 2020-02-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200223_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='initiation',
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_confirmation', to='core.DeclarationOfIntent'),
        ),
    ]
