# Generated by Django 3.0.5 on 2020-04-19 12:24

import django.core.validators
from django.db import migrations, models
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee_absolute',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee_value',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=resource_hub.core.fields.CurrencyField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_absolute_value',
            field=models.IntegerField(default=0, verbose_name='Absolute fee value'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_relative_value',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Relative fee'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='currency',
            field=resource_hub.core.fields.CurrencyField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='currency',
            field=resource_hub.core.fields.CurrencyField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=resource_hub.core.fields.CurrencyField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
