# Generated by Django 3.0.5 on 2020-04-19 15:40

import django.core.validators
from django.db import migrations, models
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200419_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee_absolute_value',
            field=models.IntegerField(default=0, help_text='A constant value that is added to every transaction', verbose_name='Absolute fee'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee_relative_value',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, help_text='A relative value that is based on the total value of a transaction', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Relative fee (%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee_tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate applied to payement fee (%)'),
        ),
    ]
