# Generated by Django 3.0.5 on 2020-04-25 10:23

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200419_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='de', max_length=2, null=True),
        ),
    ]
