# Generated by Django 3.0.5 on 2020-04-25 11:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200425_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocedure',
            name='is_invoicing',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='DE', max_length=2, null=True),
        ),
    ]
