# Generated by Django 3.0.3 on 2020-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200226_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_fixed_term',
            field=models.BooleanField(default=True),
        ),
    ]
