# Generated by Django 3.0.5 on 2020-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200425_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprocedure',
            name='is_invoicing',
            field=models.BooleanField(blank=True, default=True, help_text='Create invoices upon settlement of claims', verbose_name='Create invoices'),
        ),
    ]
