# Generated by Django 3.0.5 on 2020-04-27 13:37

from django.db import migrations, models
import django.db.models.deletion
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200425_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'send')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='creditor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_creditor', to='core.Actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=resource_hub.core.fields.CurrencyField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_debitor', to='core.Actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('i', 'initializing'), ('p', 'pending'), ('f', 'finalized'), ('fa', 'failed'), ('ca', 'canceled'), ('r', 'refunded')], default='i', max_length=2),
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.Notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
