# Generated by Django 3.0.3 on 2020-03-03 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200301_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='claim',
            name='period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
