# Generated by Django 3.0.3 on 2020-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200303_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='claim',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='total',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='unit',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
