# Generated by Django 3.0.3 on 2020-03-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200305_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept', models.BooleanField(default=False)),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='terms and conditions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('tax_rate', models.IntegerField(default=0, verbose_name='tax rate applied to prices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_methods', models.ManyToManyField(blank=True, to='core.PaymentMethod')),
                ('prices', models.ManyToManyField(to='core.Price')),
                ('trigger', models.ManyToManyField(blank=True, related_name='procedure', to='core.ContractTrigger')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure'),
            preserve_default=False,
        ),
    ]
