# Generated by Django 3.0.5 on 2020-04-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_auto_20200428_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='typ',
            field=models.CharField(choices=[('i', 'info'), ('a', 'action')], max_length=20),
        ),
    ]
