# Generated by Django 3.0.3 on 2020-03-05 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200305_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='total',
            new_name='gross',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
        migrations.AddField(
            model_name='claim',
            name='net',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='tax_rate',
            field=models.IntegerField(default=0, verbose_name='tax rate applied in percent'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='tax_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='tax rate applied in percent'),
        ),
    ]
