# Generated by Django 3.0.3 on 2020-03-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200305_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
