# Generated by Django 3.0.3 on 2020-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200305_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='condition',
            field=models.CharField(choices=[('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='condition',
            field=models.CharField(choices=[('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined')], max_length=2),
        ),
    ]
