# Generated by Django 3.0.3 on 2020-03-07 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200306_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractprocedure',
            old_name='trigger',
            new_name='triggers',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
        migrations.RemoveField(
            model_name='contractprocedure',
            name='prices',
        ),
        migrations.AddField(
            model_name='price',
            name='discounts',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PriceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate applied in percent')),
                ('addressee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='price_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PriceProfile'),
        ),
        migrations.AddField(
            model_name='contractprocedure',
            name='price_profiles',
            field=models.ManyToManyField(to='core.PriceProfile'),
        ),
    ]
