# Generated by Django 3.0.5 on 2020-04-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contract_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttrigger',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracttrigger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='typ',
            field=models.CharField(choices=[('i', 'info'), ('a', 'action'), ('c', 'contract'), ('m', 'monetary')], max_length=30),
        ),
    ]
