# Generated by Django 3.0.3 on 2020-03-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200307_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocedure',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Actor'),
            preserve_default=False,
        ),
    ]
