# Generated by Django 3.0.5 on 2020-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200429_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractprocedure',
            name='termination_period',
            field=models.IntegerField(default=0, help_text='Upon termination all claims within the termination period will be charged regardlessly', verbose_name='Termination period (days)'),
        ),
    ]
