# Generated by Django 3.0.5 on 2020-04-30 16:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200430_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
        migrations.AddField(
            model_name='claim',
            name='state',
            field=models.CharField(default='i', max_length=2),
        ),
        migrations.AddField(
            model_name='claim',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(default='i', max_length=2),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='condition',
            field=models.CharField(choices=[('i', 'initializing'), ('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='condition',
            field=models.CharField(choices=[('i', 'initializing'), ('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2),
        ),
    ]
