# Generated by Django 3.0.3 on 2020-03-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contractprocedure_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocedure',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
