# Generated by Django 3.0.5 on 2020-04-30 16:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200430_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.CharField(default='i', max_length=2),
        ),
        migrations.AddField(
            model_name='notification',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state'),
        ),
    ]
