# Generated by Django 3.0.3 on 2020-03-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contractprocedure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractprocedure',
            name='price_profiles',
        ),
        migrations.AddField(
            model_name='priceprofile',
            name='contract_procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure'),
            preserve_default=False,
        ),
    ]
