# Generated by Django 3.0.5 on 2020-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200430_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='state',
            field=models.CharField(choices=[('p', 'PENDING')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('p', 'PENDING')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='condition',
            field=models.CharField(choices=[('p', 'PENDING'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('p', 'PENDING')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('p', 'PENDING')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='condition',
            field=models.CharField(choices=[('p', 'PENDING'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2),
        ),
    ]
