# Generated by Django 3.0.4 on 2020-03-08 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200308_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceprofile',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
