# Generated by Django 3.0.4 on 2020-03-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200308_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceprofile',
            name='addressee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Actor'),
        ),
    ]
