# Generated by Django 3.0.4 on 2020-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200311_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='discounted_net',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
