# Generated by Django 3.0.4 on 2020-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_claim_discounted_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprocedure',
            name='payment_methods',
            field=models.ManyToManyField(to='core.PaymentMethod'),
        ),
    ]
