# Generated by Django 3.0.4 on 2020-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200313_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (EUR)')], default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Price'),
        ),
    ]
