# Generated by Django 3.0.4 on 2020-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200313_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
