# Generated by Django 3.0.5 on 2020-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200510_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
