# Generated by Django 3.0.4 on 2020-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_location_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PriceProfile'),
        ),
    ]
