# Generated by Django 3.0.5 on 2020-05-22 12:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import resource_hub.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200511_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bank_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BankAccount', verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='email_public',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (public)'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='info_text',
            field=models.TextField(blank=True, null=True, verbose_name='Info text'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_additional_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Invoice additional text'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_footer_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Invoice footer text'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_introductory_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Invoice introductory text'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_logo_image',
            field=models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='images/', verbose_name='Invoice logo image'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_numbers_prefix',
            field=models.CharField(default='RH', max_length=5, verbose_name='Invoice numbers prefix'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_numbers_prefix_cancellations',
            field=models.CharField(default='CAN', max_length=5, verbose_name='Invoice numbers prefix (cancellations)'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tax-ID'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='telephone_private',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone (private)'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='telephone_public',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone (public)'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT-ID'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='DE', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Street number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Account holder'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='discount',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='discounted_net',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Discounted net'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='gross',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Gross'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='net',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Net'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='period_end',
            field=models.DateTimeField(verbose_name='Performance period end'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='period_start',
            field=models.DateTimeField(verbose_name='Performance period start'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='state',
            field=models.CharField(default='p', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate applied in percent'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='unit',
            field=models.CharField(max_length=5, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='acceptance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_acceptance', to='core.DeclarationOfIntent', verbose_name='Acceptance'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='confirmation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_confirmation', to='core.DeclarationOfIntent', verbose_name='Confirmation'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure', verbose_name='Contract Procedure'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='creditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditor', to='core.Actor', verbose_name='Creditor'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='debitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debitor', to='core.Actor', verbose_name='Debitor'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_fixed_term',
            field=models.BooleanField(default=True, verbose_name='Is fixed term'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PaymentMethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PriceProfile', verbose_name='Price profile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(default='p', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='termination_period',
            field=models.IntegerField(default=0, verbose_name='Termination period'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms_and_conditions',
            field=models.TextField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Automatically accept the booking?', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='name',
            field=models.CharField(help_text='Give the procedure a name so you can identify it easier', max_length=64, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='payment_methods',
            field=models.ManyToManyField(help_text='Choose the payment methods you want to use for this venue', to='core.PaymentMethod', verbose_name='Payment methods'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='settlement_interval',
            field=models.IntegerField(choices=[(7, 'weekly'), (14, 'biweekly'), (30, 'monthly')], default=7, verbose_name='Settlement interval'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate applied in percent'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='triggers',
            field=models.ManyToManyField(blank=True, related_name='procedure', to='core.ContractTrigger', verbose_name='Triggers'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='condition',
            field=models.CharField(choices=[('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='contracttrigger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='declarationofintent',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='declarationofintent',
            name='ip_routable',
            field=models.BooleanField(default=True, verbose_name='IP routable'),
        ),
        migrations.AlterField(
            model_name='declarationofintent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='declarationofintent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.Gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'critical')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_recipient', to='core.Actor', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_sender', to='core.Actor', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(default='p', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='typ',
            field=models.CharField(choices=[('i', 'info'), ('a', 'action'), ('c', 'contract'), ('m', 'monetary')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.Notification', verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.IntegerField(choices=[(0, 'member'), (1, 'administrator'), (2, 'owner')], default=0, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_creditor', to='core.Actor', verbose_name='Creditor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_debitor', to='core.Actor', verbose_name='Debitor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PaymentMethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(default='p', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='condition',
            field=models.CharField(choices=[('p', 'pending'), ('w', 'waiting'), ('r', 'running'), ('d', 'disputing'), ('f', 'finalized'), ('x', 'expired'), ('c', 'canceled'), ('n', 'declined'), ('t', 'terminated')], max_length=2, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee_tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate applied to payement fee (%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_prepayment',
            field=models.BooleanField(default=False, help_text='If activated, claims within the following settlement interval are charged in advance', verbose_name='Prepayment?'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='price',
            name='addressee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Actor', verbose_name='Addressee'),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='price',
            name='discounts',
            field=models.BooleanField(blank=True, default=True, verbose_name='Discounts'),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='addressee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Actor', verbose_name='Addressee'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='contract_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure', verbose_name='Contract procedure'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='description',
            field=models.CharField(max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='discount',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='settlementlog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_logs', to='core.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='settlementlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='settlementlog',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AlterField(
            model_name='settlementlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='settlementlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Verified?'),
        ),
    ]
