# Generated by Django 3.0.5 on 2020-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200522_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Allow other users to link information to this location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Hide the location from feeds and only display postal code', verbose_name='Public?'),
        ),
    ]
