# Generated by Django 3.0.4 on 2020-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200316_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discounts',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
