# Generated by Django 3.0.5 on 2020-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200522_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_editable',
            field=models.BooleanField(default=False, help_text='Allow other users to link information to this location', verbose_name='Editable?'),
        ),
    ]
