# Generated by Django 3.0.5 on 2020-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200522_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Display the location in feeds and display full information', verbose_name='Public?'),
        ),
    ]
