# Generated by Django 3.0.4 on 2020-03-24 10:14

import django.core.validators
from django.db import migrations
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200322_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.999)], verbose_name='tax rate applied to payement fee'),
        ),
    ]
