# Generated by Django 3.0.5 on 2020-06-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200522_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprocedure',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Automatically accept the booking?', verbose_name='Auto accept'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='name',
            field=models.CharField(help_text='Give the procedure a name so you can identify it easier', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
    ]
