# Generated by Django 3.0.4 on 2020-03-26 18:59

import django.core.validators
from django.db import migrations
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_paymentmethod_fee_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='discount',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate applied in percent'),
        ),
        migrations.AlterField(
            model_name='contractprocedure',
            name='tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate applied in percent'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='discount',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
