# Generated by Django 3.0.9 on 2020-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='de', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='typ',
            field=models.CharField(choices=[('i', 'info'), ('a', 'action'), ('cc', 'contract created'), ('ct', 'contract terminated'), ('cd', 'contract declined'), ('ca', 'contract accepted'), ('c', 'contract'), ('m', 'monetary')], max_length=30, verbose_name='Type'),
        ),
    ]
