# Generated by Django 3.0.9 on 2020-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200820_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttrigger',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='condition',
        ),
        migrations.AddField(
            model_name='contracttrigger',
            name='event',
            field=models.CharField(choices=[('s', 'state changed'), ('i', 'invoice created')], default='s', max_length=5),
            preserve_default=False,
        ),
    ]
