# Generated by Django 3.0.4 on 2020-04-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200409_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('c', 'created'), ('b', 'booked'), ('co', 'confirmed')], max_length=3)),
                ('target', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('level', models.CharField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'critical')], max_length=3)),
                ('message', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_recipient', to='core.Actor')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_sender', to='core.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
