# Generated by Django 3.0.9 on 2020-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200921_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='unit',
            field=models.CharField(choices=[('u', 'piece'), ('m', 'minute'), ('h', 'hour'), ('d', 'day')], max_length=5, verbose_name='Unit'),
        ),
    ]
