# Generated by Django 3.0.4 on 2020-04-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='claims',
        ),
        migrations.AddField(
            model_name='claim',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='settlement_interval',
            field=models.IntegerField(choices=[(7, 'weekly'), (14, 'every two weeks'), (30, 'monthly')], default=7),
            preserve_default=False,
        ),
    ]
