# Generated by Django 3.0.9 on 2020-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200922_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='unit',
            field=models.CharField(choices=[('u', 'piece(s)'), ('m', 'minute(s)'), ('h', 'hour(s)'), ('d', 'day(s)')], max_length=5, verbose_name='Unit'),
        ),
    ]
