# Generated by Django 3.0.4 on 2020-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200413_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='settlement_interval',
        ),
        migrations.AddField(
            model_name='contractprocedure',
            name='settlement_interval',
            field=models.IntegerField(choices=[(7, 'weekly'), (14, 'every two weeks'), (30, 'monthly')], default=7),
        ),
    ]
