# Generated by Django 3.0.9 on 2020-09-23 09:29

from django.db import migrations, models
import django.db.models.deletion
import resource_hub.core.models.actors


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200923_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(max_length=255, upload_to=resource_hub.core.models.actors.actorfile_filename, verbose_name='file')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Actor', verbose_name='actor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
