# Generated by Django 3.0.9 on 2020-09-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200923_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICSFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.file',),
        ),
    ]
