# Generated by Django 3.0.4 on 2020-04-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200413_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='settlement_interval',
        ),
    ]
