# Generated by Django 3.0.9 on 2020-09-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_icsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='notification_level',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'critical')], default=1),
        ),
        migrations.CreateModel(
            name='OrganizationNotificationRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_set', to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
