# Generated by Django 3.0.9 on 2020-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200924_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='notification_level',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'critical')], default=1, help_text='You will be notified via email about notifications with the selected level and above', verbose_name='Notification level'),
        ),
    ]
