# Generated by Django 3.0.4 on 2020-04-14 20:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import resource_hub.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_contract_settlement_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=160)),
                ('invoice_no', models.CharField(db_index=True, max_length=19)),
                ('full_invoice_no', models.CharField(db_index=True, max_length=190)),
                ('is_cancellation', models.BooleanField(default=False)),
                ('invoice_from_name', models.CharField(max_length=190, null=True)),
                ('invoice_from_postal_code', models.CharField(max_length=190, null=True)),
                ('invoice_from_city', models.CharField(max_length=190, null=True)),
                ('invoice_from_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('invoice_from_tax_id', models.CharField(max_length=190, null=True)),
                ('invoice_from_vat_id', models.CharField(max_length=190, null=True)),
                ('invoice_to', models.TextField()),
                ('invoice_to_company', models.TextField(null=True)),
                ('invoice_to_name', models.TextField(null=True)),
                ('invoice_to_street', models.TextField(null=True)),
                ('invoice_to_postal_code', models.CharField(max_length=190, null=True)),
                ('invoice_to_city', models.TextField(null=True)),
                ('invoice_to_state', models.CharField(max_length=190, null=True)),
                ('invoice_to_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('invoice_to_vat_id', models.TextField(null=True)),
                ('invoice_to_beneficiary', models.TextField(null=True)),
                ('date', models.DateField(default=resource_hub.core.models.today)),
                ('locale', models.CharField(default='de', max_length=50)),
                ('introductory_text', models.TextField(blank=True)),
                ('additional_text', models.TextField(blank=True)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('payment_provider_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('foreign_currency_display', models.CharField(blank=True, max_length=50, null=True)),
                ('foreign_currency_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('foreign_currency_rate_date', models.DateField(blank=True, null=True)),
                ('shredded', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=resource_hub.core.models.invoice_filename)),
                ('internal_reference', models.TextField(blank=True)),
                ('custom_field', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('date', 'invoice_no'),
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='invoice_additional_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='invoice_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='invoice_introductory_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='invoice_numbers_prefix',
            field=models.CharField(default='RH', max_length=5),
        ),
        migrations.AddField(
            model_name='actor',
            name='invoice_numbers_prefix_cancellations',
            field=models.CharField(default='CAN', max_length=5),
        ),
        migrations.AddField(
            model_name='actor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'closed')], default='o', max_length=3),
        ),
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('tax_name', models.CharField(max_length=190)),
                ('event_date_from', models.DateTimeField(null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.Invoice')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.Contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='core.Invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('contract', 'prefix', 'invoice_no')},
        ),
    ]
