# Generated by Django 3.1 on 2020-09-30 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200924_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('state', models.CharField(default='p', max_length=2, verbose_name='State')),
                ('state_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state', verbose_name='State changed at')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('context', models.JSONField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='InvoiceCreatedEvent',
            fields=[
                ('contractevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contractevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.contractevent',),
        ),
        migrations.CreateModel(
            name='StateChangedEvent',
            fields=[
                ('contractevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contractevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.contractevent',),
        ),
    ]
