# Generated by Django 3.0.4 on 2020-04-14 21:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200414_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceposition',
            name='gross_value',
        ),
        migrations.RemoveField(
            model_name='invoiceposition',
            name='tax_name',
        ),
        migrations.RemoveField(
            model_name='invoiceposition',
            name='tax_value',
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='discount',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='discounted_net',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='gross',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='item',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='net',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='price',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='unit',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='tax_rate',
            field=resource_hub.core.fields.PercentField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate applied in percent'),
        ),
    ]
