# Generated by Django 3.0.5 on 2020-04-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200414_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='invoice_logo_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
