# Generated by Django 3.0.5 on 2020-04-15 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_actor_invoice_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
