# Generated by Django 3.0.5 on 2020-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_contract_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='invoice_additional_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_footer_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_introductory_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoice_logo_image',
            field=models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='images/'),
        ),
    ]
