# Generated by Django 3.0.5 on 2020-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_settlementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_prepayment',
            field=models.BooleanField(default=False),
        ),
    ]
