# Generated by Django 3.0.5 on 2020-04-16 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_paymentmethod_is_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_prepayment',
            field=models.BooleanField(default=False, help_text='If activated claims within the first settlement interval are charged immediatly'),
        ),
    ]
