# Generated by Django 3.1 on 2020-10-05 23:28

from django.db import migrations, models
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopbooking',
            name='workplaces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workplaces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workshopcontract',
            name='equipment',
            field=resource_hub.core.fields.CustomManyToManyField(blank=True, help_text='Services or additional equipment for the workshop', through='workshops.EquipmentBooking', to='workshops.WorkshopEquipment', verbose_name='WorkshopEquipment'),
        ),
    ]
