# Generated by Django 2.2.4 on 2019-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_public',
            field=models.BooleanField(default=True, verbose_name='First and last name public'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
