# Generated by Django 3.0.3 on 2020-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttrigger',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='meta',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_absolute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_value',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='TriggerMeta',
        ),
    ]
