# Generated by Django 2.2.4 on 2019-10-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191027_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_public',
        ),
    ]
