# Generated by Django 2.2.4 on 2019-09-20 17:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0004_auto_20190918_1806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='group',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AddField(
            model_name='organization',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
    ]
