# Generated by Django 2.2.4 on 2019-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191122_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('mem', 'Member'), ('adm', 'Administrator'), ('own', 'Owner')], default='mem', max_length=3),
        ),
    ]
