# Generated by Django 3.0.3 on 2020-02-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200212_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_call', models.CharField(max_length=128)),
                ('condition', models.CharField(choices=[('p', 'pending'), ('co', 'confirmed'), ('a', 'accepted'), ('f', 'finalized'), ('d', 'disputed'), ('x', 'expired'), ('c', 'canceled')], max_length=2)),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(max_length=64)),
                ('provider_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(default='images/default.png', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='function_call',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='owner',
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('p', 'pending'), ('co', 'confirmed'), ('a', 'accepted'), ('f', 'finalized'), ('d', 'disputed'), ('x', 'expired'), ('c', 'canceled')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ContractTrigger',
        ),
        migrations.AddField(
            model_name='trigger',
            name='meta',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.PROTECT, to='core.TriggerMeta'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='trigger_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Trigger'),
            preserve_default=False,
        ),
    ]
