# Generated by Django 3.0 on 2019-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='/static/default.png', null=True, upload_to='images/'),
        ),
    ]
