# Generated by Django 3.1 on 2020-10-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0043_auto_20200930_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.paymentmethod',),
        ),
    ]
