# Generated by Django 3.0.5 on 2020-04-17 18:12

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('thumbnail_original', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('dtstart', models.DateTimeField()),
                ('dtend', models.DateTimeField()),
                ('dtlast', models.DateTimeField()),
                ('is_public', models.BooleanField(blank=True, default=True)),
                ('recurrences', recurrence.fields.RecurrenceField(blank=True)),
                ('thumbnail_original', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('thumbnail_original', models.ImageField(default='images/default.png', null=True, upload_to='images/')),
                ('bookable', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('contract_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gallery')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='VenuePrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Price')),
                ('venue_ptr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_price', to='venues.Venue')),
            ],
            bases=('core.price',),
        ),
        migrations.CreateModel(
            name='VenueContractProcedure',
            fields=[
                ('contractprocedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContractProcedure')),
                ('venues', models.ManyToManyField(to='venues.Venue')),
            ],
            bases=('core.contractprocedure',),
        ),
        migrations.CreateModel(
            name='VenueContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contract')),
                ('equipment', models.ManyToManyField(blank=True, to='venues.Equipment')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='venues.Event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.contract',),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_created_by', to='core.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_actor', to='core.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='venues.EventTag'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_updated_by', to='core.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(to='venues.Venue'),
        ),
        migrations.CreateModel(
            name='EquipmentPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Price')),
                ('equipment_ptr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_price', to='venues.Equipment')),
            ],
            bases=('core.price',),
        ),
        migrations.AddField(
            model_name='equipment',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venues.Venue'),
        ),
    ]
