# Generated by Django 3.0.3 on 2020-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VenueUsageContract',
            new_name='VenueContract',
        ),
        migrations.AddField(
            model_name='venuecontractprocedure',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venuecontractprocedure',
            name='tax_rate',
            field=models.IntegerField(default=0, verbose_name='tax rate applied to prices'),
        ),
    ]
