# Generated by Django 3.0.3 on 2020-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20200223_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
