# Generated by Django 3.0.3 on 2020-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20200223_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
