# Generated by Django 3.0.3 on 2020-02-27 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20200224_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dtend',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dtstart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
