# Generated by Django 3.0.9 on 2020-08-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200820_1326'),
        ('venues', '0005_auto_20200825_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contract_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='core.ContractProcedure', verbose_name='Contract procedure'),
        ),
    ]
