# Generated by Django 3.0.3 on 2020-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_auto_20200227_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dtend',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='dtstart',
            field=models.DateTimeField(),
        ),
    ]
