# Generated by Django 3.0.3 on 2020-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20200227_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail_original',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
