# Generated by Django 3.0.3 on 2020-02-28 12:22

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_auto_20200228_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True),
        ),
    ]
