# Generated by Django 3.0.3 on 2020-02-28 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_auto_20200228_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dtlast',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
