# Generated by Django 3.0.9 on 2020-08-25 11:11

from django.db import migrations, models
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_auto_20200825_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='usage',
        ),
        migrations.AddField(
            model_name='venue',
            name='usage_types',
            field=resource_hub.core.fields.MultipleChoiceArrayField(base_field=models.CharField(choices=[('o', 'other'), ('w', 'workshop')], default='o', max_length=3, verbose_name='Usage type'), default=['o'], help_text='Describe which activites are possible', size=None, verbose_name='Usage types'),
            preserve_default=False,
        ),
    ]
