# Generated by Django 3.0.3 on 2020-03-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200305_1039'),
        ('venues', '0010_venuecontractprocedure_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='auto_accept',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='trigger',
        ),
        migrations.AddField(
            model_name='venuecontractprocedure',
            name='contractprocedure_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ContractProcedure'),
            preserve_default=False,
        ),
    ]
