# Generated by Django 3.0.9 on 2020-08-27 09:45

from django.db import migrations, models
import resource_hub.core.fields
import resource_hub.venues.models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_auto_20200827_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='usage_types',
            field=resource_hub.core.fields.MultipleChoiceArrayField(base_field=models.CharField(choices=[('o', 'other'), ('w', 'workshop')], max_length=3), default=resource_hub.venues.models.get_default_usage, help_text='Describe which activites are possible', size=None, verbose_name='Usage types'),
        ),
    ]
