# Generated by Django 3.0.3 on 2020-03-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200307_1613'),
        ('venues', '0011_auto_20200305_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='contract_procedure',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='max_price_per_d',
        ),
        migrations.RemoveField(
            model_name='venuecontractprocedure',
            name='price_per_h',
        ),
        migrations.AddField(
            model_name='equipment',
            name='apply_price_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='equipment',
            field=models.ManyToManyField(to='venues.Equipment'),
        ),
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price'),
        ),
        migrations.AddField(
            model_name='venuecontract',
            name='venues',
            field=models.ManyToManyField(to='venues.Venue'),
        ),
        migrations.AddField(
            model_name='venuecontractprocedure',
            name='venues',
            field=models.ManyToManyField(to='venues.Venue'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price'),
        ),
    ]
