# Generated by Django 3.0.9 on 2020-08-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20200827_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbooking',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_bookings', to='venues.VenueContract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_bookings', to='venues.Equipment', verbose_name='Equipment'),
        ),
    ]
