# Generated by Django 3.0.9 on 2020-09-23 09:29

from django.db import migrations
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_auto_20200828_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venues',
            field=resource_hub.core.fields.CustomManyToManyField(to='venues.Venue', verbose_name='Venues'),
        ),
    ]
