# Generated by Django 3.0.4 on 2020-03-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200313_0922'),
        ('venues', '0014_auto_20200310_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contract_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ContractProcedure'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail_original',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
