# Generated by Django 3.1 on 2020-10-04 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200930_0845'),
        ('venues', '0014_auto_20200923_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='price',
        ),
        migrations.AddField(
            model_name='venue',
            name='base_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.price', verbose_name='Base price'),
        ),
        migrations.AddField(
            model_name='venue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contract_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contractprocedure', verbose_name='Contract procedure'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail_original',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='Thumbnail'),
        ),
    ]
