# Generated by Django 3.0.4 on 2020-03-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_location_is_public'),
        ('venues', '0015_auto_20200313_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='thumbnail_original',
            field=models.ImageField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='venues.Venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Price'),
        ),
    ]
