# Generated by Django 3.0.4 on 2020-03-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_auto_20200315_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='apply_price_profile',
        ),
    ]
