# Generated by Django 3.1 on 2020-10-10 17:41

from django.db import migrations
import resource_hub.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_auto_20201010_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontract',
            name='equipment',
            field=resource_hub.core.fields.CustomManyToManyField(blank=True, help_text='Services or additional equipment for the venue', through='venues.EquipmentBooking', to='venues.Equipment', verbose_name='Equipment'),
        ),
    ]
