# Generated by Django 3.0.4 on 2020-03-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200316_1348'),
        ('venues', '0017_remove_equipment_apply_price_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Price')),
                ('venue_ptr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_price', to='venues.Venue')),
            ],
            bases=('core.price',),
        ),
        migrations.CreateModel(
            name='EquipmentPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Price')),
                ('equipment_ptr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_price', to='venues.Equipment')),
            ],
            bases=('core.price',),
        ),
    ]
