# Generated by Django 3.0.4 on 2020-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_equipmentprice_venueprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail_original',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
