# Generated by Django 3.0.4 on 2020-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_auto_20200325_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontract',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='venues.Equipment'),
        ),
    ]
